### ISSUE TITLE
dinamik char dizi

### ISSUE THREAD

**Issue by ghost** [BilgisayarKavramlari/Programlamaya-Giris#190]
dinamik char dizisi oluşturarak klavyeden string okumaya çalışıyorum ama bir noktada hata yapıyorum çözemedim 

#include <stdio.h>
#include <stdlib.h>
int main()
{
    int yaziUzunlugu;
    printf("Yazının uzunluğunu giriniz: ");
    fscanf(stdin,"%u",&yaziUzunlugu);
    char **string = (char*)malloc(sizeof(char)*yaziUzunlugu);
    printf("Yazı giriniz: ");
    gets(string);
    printf("%s",string);
    free(string);
    return 0;
}

yazdığım kod bu lütfen conio.h kütüphanesinden fonksiyon kullanmayınız

**Comment by Kaalealma** [comment]
char *string = (char)malloc(sizeof(char)*yaziUzunlugu); yerine
baştaki parantez içindeki charın yanına yildiz koy

gets(string); yerine
scanf("%s", string)

yazarsan çalışıyor sanırım

Ne yapmak istediğini anlamadım ancak aynı işi şu kod görüyor

#include <stdio.h>
#include <stdlib.h>
int main()
{
char *string;
printf("Yazı giriniz: ");
scanf("%s", string);
printf("%s",string);
free(string);
return 0;
}

Kaç adet karakter girişi yapılacağına dair bilgi vermemiz gereksiz gibi duruyor.
Zaten bu değeri girsek bile bu sınırı aşabiliyoruz ya da daha az sayıda karakter girebiliyoruz.

**Comment by ghost** [comment]
yapmak istediğim dışarıdan sayı girerek dinamik dizi oluşturmak bu oluşturduğum dinamik dizi içine yazı(string) yazmak scanf kullanmamamın nedeni boşluk karakterine kadar alması

**Comment by Kaalealma** [comment]
Acemiyim biraz 

gets fonksiyonundan önce
fflush(stdin);
fonksiyonunu kullanınca çalışıyor

yani sanırım ^^
sorun getsin çalışmaması ise çalışmaya başlıyor

**Comment by ghost** [comment]
bende fark ettim gets ile scanf iyi geçinemiyor :D ilk scanf çalıştığı zaman gets fonksiyonu çalışmıyor

**Comment by ghost** [comment]
#include <stdio.h>
#include <stdlib.h>
char *yaziGirisi(int);
int main()
{
    int yaziUzunlugu;
    printf("Yazının uzunluğunu giriniz: ");
    fscanf(stdin,"%u",&yaziUzunlugu);
    fgetc(stdin);
    char *tut = yaziGirisi(yaziUzunlugu);
    for(int i = 0; i < yaziUzunlugu; i++)
    {
        fprintf(stdout,"%c\n",tut[i]);
    }
    free(tut);
    return 0;
}

char *yaziGirisi(int uzunluk)
{
    char *string = (char *)malloc(sizeof(char)*uzunluk);
    fprintf(stdout,"Yazı giriniz: ");
    fgets(string,uzunluk+1,stdin);
    return string;
}

bir kaç değişiklik yaparak sonunda çalıştırmayı başardım :D aklınızda bulunsun scanf fonksiyonu ile gets fonksiyonu birlikte çalışmıyor araya getc fonksiyonu eklenirse güzel güzel çalışıyor :)
