### ISSUE TITLE
garip bir durum kayan noktalı sayılar için 

### ISSUE THREAD

**Issue by ghost** [BilgisayarKavramlari/Programlamaya-Giris#215]
![screenshot from 2017-01-27 15-05-13](https://cloud.githubusercontent.com/assets/11363276/22370356/186f8e66-e4a2-11e6-806b-c0f20926519f.png)

normalde çıktının 3.14159265358979323846 bu şekilde olmasını beklerim ama çıktı 3.14159265358979311600 bu şekilde

**Comment by tcelik** [comment]
Kayan noktalı sayıları 2 lik tabanda represente edemediğimiz bilgisi burada karşımıza çıkıyor.

if ( 1.3 == 1.3) bile yanlış sonuçlar doğurabiliyor.

**Comment by Kaalealma** [comment]
"It is commonly known simply as double. The IEEE 754 standard specifies a binary64 as having:

Sign bit: 1 bit
Exponent: 11 bits
Significand precision: 53 bits (52 explicitly stored)

This gives 15–17 significant decimal digits precision."

[Kaynak](https://en.wikipedia.org/wiki/Double-precision_floating-point_format)

Ya da 
http://imgur.com/a/ZJcGn
Double değişkeninin hassaslığı 15 basamak gözüküyor.
[Kaynak](https://software.intel.com/en-us/articles/introduction-to-x64-assembly)

Sanırım bunlarla ilgili bir şey

**Comment by ghost** [comment]
teşekkürler :)
