### ISSUE TITLE
Clone Hatasi

### ISSUE THREAD

**Issue by ugurbozkurt** [BilgisayarKavramlari/Programlamaya-Giris#642]
remote: Enumerating objects: 889, done.        
remote: Total 889 (delta 0), reused 0 (delta 0), pack-reused 889                
Receiving objects: 100% (889/889), 174.51 KiB | 544.00 KiB/s, done.             
Resolving deltas: 100% (189/189), done.                                         
error: invalid path 'Python'da Ekrana "Merhaba Dünya" bastırma'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by Mustafa037** [comment]
Çözdün mü?
